### ISSUE TITLE
Time Series Snippets

### ISSUE THREAD

**Issue by franzbischoff** [matrix-profile-foundation/tsmp#19]
Imani S, Madrid F, Ding W, Crouter S, Keogh E. Matrix Profile XIII : Time Series Snippets : A New Primitive for Time Series Data Mining. 

https://sites.google.com/site/snippetfinderinfo/

**Comment by chris-english** [comment]
franz, I am in the very preliminary stages of playing with TSMP, running examples, reading the code, the many papers, and was hoping to find the supporting page of SnippetFinder. I did find Eamonn on Stackoverflow [SOF](https://stackoverflow.com/questions/48641665/identifying-repeated-sequences-of-numbers-in-time-series) and asked about it. I imagine they got some unfriendly letter from ArcGIS about trade dress infringement and had to take the site down.

I can promise I'm not very good at coding but would like to help expand this package. Chris

**Comment by franzbischoff** [comment]
Hi, thank you for your interest. I have the materials to implement this feature in TSMP. I just need time to address other priorities first. Would be glad if you can help.
You can contact me using the e-mail that is in the package description.
Best regards.

**Comment by franzbischoff** [comment]
![image](https://user-images.githubusercontent.com/984592/59724475-e3817900-9221-11e9-9198-2cc7cb90592b.png)
