### ISSUE TITLE
Problem similar to bug #28 for smaller/different data set

### ISSUE THREAD

**Issue by xenmind** [matrix-profile-foundation/tsmp#29]
Hi Franz,

As per Run 3 of the earlier bug (https://github.com/franzbischoff/tsmp/issues/28), I'm getting the following error when I use different data: 'Error in candi_dist[j] <- temp[rlt_idx] : replacement has length zero.' The new data is here: https://www.dropbox.com/s/k0ed9curkaqjpry/data.csv?dl=0. The code to replicate is here: https://www.dropbox.com/s/xql8odgj1yoxxew/tsmp_repro_eg2.r?dl=0. Also, I get the same error for one of the previous working Runs but using a different annotation algorithm (which I can provide if useful).

Thanks,
Gavin.

**Comment by franzbischoff** [comment]
Sorry for the delay. Working on other priorities. I'll address this asap.
