### ISSUE TITLE
sdts_predict producing wrong number of predictions.

### ISSUE THREAD

**Issue by xenmind** [matrix-profile-foundation/tsmp#30]
Hi,

I noticed that while the sdts model building completes, the length of predictions is not what's expected. For windows of c(110, 220, 330) say, I'd expect the length of the predictions to be around: length(te_label)-round(mean(w)), i.e. 220 or so shorter. However, in the following example, data: https://www.dropbox.com/s/k0ed9curkaqjpry/data.csv?dl=0 and code: https://www.dropbox.com/s/vd9ahjssuzci13k/tsmp_repro_eg3.r?dl=0 when 'strt' is set to 1 the following warning is thrown: 'In max(dist_pro[[fit_idx]][!is.infinite(dist_pro[[fit_idx]])]) :
  no non-missing arguments to max; returning -Inf' and the length of predictions is 1470 (only 30 shorter than te_label). When I set strt to 40,000, there is no warning but the prediction is 1549 in length, i.e. longer than te_label.

Gavin.

**Comment by franzbischoff** [comment]
Hi @xenmind, thanks for your reports. SDTS would be getting my attention later as it is already a framework using time-series, differently from the rest of the package. But your reports are pushing me towards it (and that is good, don't worry! 👍 ).
I think I'll have to take some proper time to test it with several datasets; I would appreciate if you can provide me "buggy" ones so I can try to figure out the problems and tweak it.
As you can see SDTS receives multiple window_size's (can receive only one if you want). But internally, even the original code, didn't address all the exceptions this could generate, so this is being a pain in the neck. Also, I discover that the original MATLAB code handles NA's softly but R is stubborn (and correct) and any NA that doesn't have an explicit way to handle, throws an error.

Please be patient for now :)

**Comment by xenmind** [comment]
No problem, please take your time, I'm in no hurry, just trying to get an intuition for such a cool model. If I find anything else I'll let you know.

**Comment by franzbischoff** [comment]
Hi the data.csv file seems to be corrupt, there is only one column

**Comment by xenmind** [comment]
Sorry just saw this, not sure what happened. I have reuploaded the data and confirmed the code is still working with it. Data: https://www.dropbox.com/s/26q2nkk5eitwjk4/data.csv?dl=0

**Comment by franzbischoff** [comment]
Bug confirmed. I'll work on it ASAP

**Comment by franzbischoff** [comment]
check your syntax at sdts_score:

`sdts_score(pred, te_label, 1)`
