### ISSUE TITLE
SCRIMP not able to handle missing values in time-series dataset

### ISSUE THREAD

**Issue by dipayandev** [matrix-profile-foundation/tsmp#32]
**While running the tsmp function with mode='tsmp', the code is failing with the following error:**

PRE-SCRIMP [---------------------------]   0% at 23 it/s, elapsed:  3s, eta: 36mError in matrix_profile[update_pos] <- distance_profile[update_pos] : 
  NAs are not allowed in subscripted assignments

**To Reproduce**
I used the following code

```
orig_data <- read.csv("dataset.csv", header=TRUE,nrows=50000)

#Working with tsmp: 
library("tsmp", lib.loc="~/R/win-library/3.5")
mp <- tsmp(orig_data$VALUENUM, window_size = 4, mode="scrimp")
View(mp)
#Plotting: 
plot(mp$mp, type = 'o')
```
**Please make sure to add few empty/NA values in the column VALUENUM**

**Additional context**
The same error was not re-producible for STAMP or STOMP.

**Comment by franzbischoff** [comment]
Thank you. I'll check this ASAP.

**Comment by franzbischoff** [comment]
Hi, I couldn't reproduce the error. Can you send a sample dataset for it?
Have you tried with the last version from GitHub?
Thank you.

**Comment by dipayandev** [comment]
Hi,
The dataset I'm using is confidential, so I afraid I can't upload that. 
However, here the sample values you can use to produce the same.

![image](https://user-images.githubusercontent.com/10447363/48058988-f9d04c80-e1dd-11e8-8038-ed8db2217b0c.png)

Please try to run the MP on column - VALUE 

`library("tsmp", lib.loc="~/R/win-library/3.5")
mp <- tsmp(orig_data$VALUE, window_size = 4, mode="scrimp")
View(mp)`

> > mp <- tsmp(orig_data$VALUE, window_size = 4, mode="scrimp")
Error in matrix_profile[update_pos] <- distance_profile[update_pos] : 
  NAs are not allowed in subscripted assignments
> View(mp)

**Comment by franzbischoff** [comment]
Sure, I just need a sample that can reproduce the error. I'll try with this you provided.

**Comment by franzbischoff** [comment]
It works here. I'm using TSMP version 0.3.2

```
> tsmp(data, window_size = 4, mode="scrimp")
Finished in 0.00 secs
Matrix Profile
--------------
Profile size = 9 
Window size = 4 
Exclusion zone = 2 
Contains 1 set of data with 12 observations and 1 dimension

> str(tsmp(data, window_size = 4, mode="scrimp"))
Finished in 0.00 secs
List of 9
 $ mp  : num [1:9, 1] 0.494 1.614 1.614 1.623 1.078 ...
 $ pi  : num [1:9, 1] 9 6 7 8 1 2 3 4 1
 $ rmp : num [1:9, 1] Inf Inf Inf Inf Inf ...
 $ rpi : num [1:9, 1] -1 -1 -1 -1 -1 -1 -1 -1 -1
 $ lmp : num [1:9, 1] Inf Inf Inf Inf Inf ...
 $ lpi : num [1:9, 1] -1 -1 -1 -1 -1 -1 -1 -1 -1
 $ w   : num 4
 $ ez  : num 0.5
 $ data:List of 1
  ..$ : num [1:12, 1] 7.29 NA -1 1.23 89.3 NA NA 67.2 78.2 NA ...
 - attr(*, "class")= chr "MatrixProfile"
```

**Comment by dipayandev** [comment]
Probably I'm using the older version then. Let me upgrade the version again, and get back. If all good, we can close this issue :)

**Comment by dipayandev** [comment]
Not sure what's the issue is :)
```
> packageVersion("tsmp")
[1] ‘0.3.2’
```

**Comment by franzbischoff** [comment]
Please try the last one from github:

`devtools::install_github("franzbischoff/tsmp")`

**Comment by dipayandev** [comment]
That's working for me now. Thanks
