### ISSUE TITLE
Comparing Matrix Profiles

### ISSUE THREAD

**Issue by chris-english** [matrix-profile-foundation/tsmp#40]
**Is your feature request related to a problem? Please describe.**
A series of matrix profile are built. Set A, Set B.
**Describe the solution you'd like**
Is it possible to use the constructed (built by tsmp) matrix profiles, to compare A & B. It currently appears that one must reconstruct matrix profiles, what is deemed 'an expense', by Keogh et al
to achieve such comparison, though perhaps I just don't understand how I might use the tsmp notation to use resources (Set A & Set B matrix profiles) appropriately.
**Describe alternatives you've considered**
There is a clear need to foment something of a discussion about Matrix Profile in R over at Stackoverflow. Eammon is in there discussing in Statsexchange and CrossValidated, but suggests people contact him directly for advice rather than answering more than general questions.

tsmp is great, and I'm very happy you've gotten Valmod up and running. What is missing, in the face of rising interest, is a kind of 'how to' once one has used tsmp to construct mp type objects.

Consider this scenario:

A time series that is too long to be kept in memory and needs to be split into subsets. Tens, hundreds, or thousands of yet smaller time series that may or may not be a subset of any one of the long time series.

This is essentially what one kaggle competition looks like currently. Everything is too big for memory, needs to be split, then needs to be compared. The competition starts with a single long training series, about 17.2G, then asks, where in training, did the test sequences, that are 150k long come from within the training sequence. Take the label at the end of that test/training and report that as answer. 

I look at all of that as fitting a test to all train, next test to all train & ect, and an indexing dance in each instance to get the tag. As I am currently approaching it I get the largest segment of train that leaves me some or 1/2 of memory and make matrix profile, I make a list of test that will fit within memory and make a list of matrix profiles. And then I am, seemingly like many others, stuck as to how to proceed. 

So perhaps, I should rather be constructing a list of the largest segment of train that takes half my memory and looping through test to create the list, then on to the next segment of train and again all the instances of test. 

mp1 <- lapply(seq_along(test_segments),
function(i) {
tsmp(c(train_segment1, test_segments[[i]]), window size = & etc,

mp2 <- and again

This is the sort of fruitful discussion that I think should be happening at Stackoverflow, and I'm more than happy to be the dummy asking questions.

I think your hard, and useful work, should be documented by use cases from among the community and as I learn better I'll help answer as well. But when I start by asking, 'how can you compare to tsmp martix-profiles in R, and can't find the answer myself, it goes to a lack of examples and documentation, that I would also be happy to help with.
chris

**Additional context**

**Comment by franzbischoff** [comment]
Hello @chris-english, happy to know tsmp is being useful :-)

If I understand, you want to compare a set of time series with another set? i.e.: X1 & Y1; X1 & Y2; X2 & Y1; X2 & Y2? Never thought about that :-)

I'm trying to publish a paper about TSMP. First I've contacted the JSS that desk rejected it as they "feel
that the topic would not be easily accessible for our (broad) statistical audience". So I'm trying the R Journal, but still waiting for a reply... This paper is a "how to", that I'll add as a vignette in future releases. And yes, I plan to add more use cases to help users.

Please, feel free to open a discussion at Stackoverflow, I think it would be great!

**Comment by chris-english** [comment]
I am expecting you Stackoverflow score to 'soar', but I really want this clarified. X1& Y1:Yn is really about trying to do all this stuff on laptop with limited memory, as X1 & Y1:Yn evolves to X1:Xn &Y1:Yn.

And I was thinking about this a while, wondering if I had mp for X1 and X2 couldn't I: together <- c(X1, X2), and then remembered exclusion zones, ok duh. But, if I've already expended the cycles to establish X1, can't it be used repetitively even as Y1:Yn are being constructed. And things like that. I'll go over and start asking my Mr. Stupid questions at Stackoverflow. 

I have some specific things about Valmod that I want to take up with you, but I forked and need to make some browser() inserts to find where I'm running  into difficulties before I can present anything useful regarding 'subscript out of bounds'. I'll be back to you.

**Comment by chris-english** [comment]
I'll bcc

**Comment by tylerwmarrs** [comment]
@franzbischoff and @chris-english in regards to memory utilization, you can also consider batch processing. I am the sole creator of mass-ts, a python library implementing MASS algorithms. MASS as you know is the core algorithm that the matrix profile algorithms are built on top of. To the point, I created my own batch implementation of MASS2 that may provide you with insight into solving these types of problems. Unfortunately, I know just enough R to be dangerous, but not enough to be effective. https://github.com/tylerwmarrs/mass-ts

**Comment by franzbischoff** [comment]
Yes, I'm handling the memory in R with calls to the gc system, mainly in multithreading mode.
I'm just finishing the MPdist and Snippet Finder algorithms and I'll come back here to figure out this issue.

**Comment by franzbischoff** [comment]
I think this is solved by using the MPdist measurement.
If not, please reopen this issue.
