### ISSUE TITLE
Use of the matrix profile for clustering

### ISSUE THREAD

**Issue by JoachimGoedhart** [matrix-profile-foundation/tsmp#42]
Dear Francisco,

Thanks for your work on the tmsp package.
I'm looking into methods for clustering of time-series data that I'm implementing in shiny app for time-series analysis of scientific data (https://github.com/JoachimGoedhart/PlotTwist). The matrix profile seems like a powerful method.
Do you think that the matrix profile can be used for clustering? If so, can you help me with using the tmsp pakcage to calculate a distance matrix that I can use for clustering?

Any help would be appreciated,
Joachim.

**Comment by franzbischoff** [comment]
Sure, please contact me here: https://discord.gg/wHmAAg

**Comment by bafs84** [comment]
I would be curious as well :)
