### ISSUE TITLE
Snippet algorithm cannot be accessed

### ISSUE THREAD

**Issue by Deepakgthomas** [matrix-profile-foundation/tsmp#43]
Hi Francisco,

Firstly, thank you for the R implementation of the Matrix Profile. It is extremely useful for my analysis process.
While going over this repository, I see that you have coded the 'snippet finding' algorithm (Time Series Snippets: A New Primitive for Time Series Data Mining), however, I am unable to use it - 
snippets <- find_snippet(mp_fluss_data$walkjogrun$data[1:300], 40, n_snippets = 2)

Error in find_snippet(mp_fluss_data$walkjogrun$data[1:300], 40, n_snippets = 2) : 
  could not find function "find_snippet"

Did you by any chance remove the function from R?

Thank you,
Deepak Thomas

**Comment by franzbischoff** [comment]
Hi, I haven't remove it.

Try to update the package with the last commit from this repository:

`devtools::install_github("franzbischoff/tsmp", force = TRUE)`

If still not working, try to find the function directly:

`tsmp::find_snippet()`
or
`tsmp:::find_snippet()`

and check if you can reach it.

Best regards.

**Comment by Deepakgthomas** [comment]
I got it working using - devtools::install_github("franzbischoff/tsmp", force = TRUE)

Thank you for your quick reply Francisco!
