### ISSUE TITLE
Stomp/stamp for different length data

### ISSUE THREAD

**Issue by testereng** [matrix-profile-foundation/tsmp#44]
**Describe the bug**
Hello, was trying to play with 2 datasets for Join similarity.
When running stomp/stamp on 2 datasets of different length, starting the smallest one , I have following error:

Error in if (skip_location[i] || any(nn$par$query_sd[i] < vars()$eps)) { : 
  missing value where TRUE/FALSE needed

When I find a way to make it work (with  concatenation NA), calculation gets longer (see code below...)

**To Reproduce**
With data from the package following code fails:
a1=mp_toy_data$data[,1]  
a2=mp_toy_data$data[1:150,2]
st=stomp(a2,a1,window_size = 30)

Now if I complete a2 with "NA",no more errors:
a2=c (mp_toy_data$data[1:150,2] , rep(NA ,400))
st=stomp(a2,a1,window_size = 30)
"Finished in 1.04 secs"

Following code is 10 times more faster with same lengths ...
a1=mp_toy_data$data[,1]  
a2=mp_toy_data$data[,2]
st=stomp(a2,a1,window_size = 30)
"Finished in 0.11 secs"

**Expected behavior**
Would expect to have a Matrix Profile and Profile index  with different lengths data...

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
Thanks for your help-comments...

**Comment by franzbischoff** [comment]
This may be related with the first argument being smaller than the second.
Initially, stomp didn't allow that, but after the implementation of MPdist, I might have introduced some bug. I'll check that.

**Comment by franzbischoff** [comment]
That's it. The query must be smaller than the reference.

Later version will handle this. stamp() and stomp_par() returns the proper error message.
