### ISSUE TITLE
Time Series Snippets: Question about window_size	

### ISSUE THREAD

**Issue by Deepakgthomas** [matrix-profile-foundation/tsmp#53]
Hi Franz,

I had a question about window_size. Could you please tell me how does the window_size affect the analysis process? For instance, tsmp defaults it to s_size / 2, is there any reason behind it?
I also see that it is slightly different from the original Matlab code. The author's code included it as a percentage of the snippet length. Was the change from relative to absolute length made for any specific reason?
I'm trying to better understand the algorithm and its working. Hence the questions :)

Thanks!
Deepak

**Comment by franzbischoff** [comment]
`s_size` is the sample size, used for stamp and scrimp++ algorithm IIRC, when you don't want to compute all MP.

Can you show a code example?

**Comment by Deepakgthomas** [comment]
I have taken this example from https://rdrr.io/github/franzbischoff/tsmp/man/find_snippet.html -
snippets <- find_snippet(mp_fluss_data$walkjogrun$data, 120, n_snippets = 2, window_size=60)
I'm trying to understand how window_size works. For instance what difference would it make if this window_size is doubled or halved?

**Comment by franzbischoff** [comment]
Now I get it. 

s_size is the size of the snippet you want to find, this is not the problem, right?
here, window_size is not exactly the same as we think when building a matrix profile. The size must be smaller than s_size because the window will roll over segments of s_size's size.

**Comment by Deepakgthomas** [comment]
Well, I think I'm getting it but I still don't see its use. Did the authors write anything about this technique in their papers? If yes, can you please guide me to the section?

**Comment by franzbischoff** [comment]
Sure they did. It's not a technique, its a requirement.
Let's take for example the MPdist algorithm that is the basis of snippets: you don't compare chunks of TS2 with chunks of TS1, this is the normal AB join of Matrix Profile.

What you compare are chunks of chunks, i.e: windows_size's of s_size.

That's why there is a need to optimize the creation of ABBA profile and the use of movmin() to get this done quickly.

**Comment by Deepakgthomas** [comment]
I carefully re-read that section of the MPDist paper and I believe we are comparing chunks of TS2 with TS1 (not chunks of chunks). Honestly, I'm very new to the Matrix Profile and its applications and therefore I may be wrong, but that is my understanding as of now.
To further elucidate my point, here are snippets from the MPDist paper - 
"We begin by obtaining the All-subsequences set of Q (Definition 4), and then
calculating the distance between each individual subsequence in the set to every
subsequence in T." This distance D is then used to calculate PAB and PBA from what I perceive.

**Comment by franzbischoff** [comment]
I'll try another approach:

1. MPDist have two applications:
   - return a single number that reflects the distance between TS1 and TS2. This is accomplished using AB and BA from the known MP algorithm.
   -  return a vector that reflects not the whole distance between TS1 and TS2, but chunks of TS2 with whole TS1. If you just compare these chunks of TS2 with TS1, this is the euclidean distance that we had (i.e. stomp), so, you need to compare chunks of TS2 chunks to have multiples MPDist that forms the resulting vector. This is what is used on Snippets.

**Comment by Deepakgthomas** [comment]
Yupp, you're absolutely right. Thank you for taking your time out to
explain this to me!!!
