### ISSUE TITLE
tsmp depends on R >= 3.5.0

### ISSUE THREAD

**Issue by Derek-Jones** [matrix-profile-foundation/tsmp#76]
In misc.r there are two calls to `diag`, both passing `names=FALSE`

Support for the `names` parameter appeared in [R version 3.5.0](https://cran.r-project.org/doc/manuals/r-release/NEWS.html)

Calls to `motif` fail for pre 3.5.0 versions.

Removing both instances of this argument does not appear to to have broken anything.  But then I am new here.

**Comment by franzbischoff** [comment]
Interesting finding. Are you using an old R version?
I did use the `names` parameter for a reason. 
I will add the restriction for R >= 3.5.0.

**Comment by Derek-Jones** [comment]
I am working on a book and use lots of packages, so updating will be a hassle.
Draft pdf and data here: http://www.knosof.co.uk/ESEUR/

At the moment I'm experimenting with the data I have.  Another error crops up if the window size is too big, which looks like it's related to my removal of the `names` argument.

I will have to update my R system at some point.

**Comment by franzbischoff** [comment]
Hi, I'll close this issue. About updating R, it is strongly recommended, and easier than you think. Try the  [installr](https://github.com/talgalili/installr) package.
