### ISSUE TITLE
Prediction with matrix profile

### ISSUE THREAD

**Issue by MislavSag** [matrix-profile-foundation/tsmp#77]
Thanks for the great package!

Can you use a matrix profile for prediction? Is there a function (in the package) that helps to implement prediction based on motifs. For example, let's say I want to predict the values of the time series for the next 3 periods based on the 30-period window. I would search for similar (based on euclidian distance) 30-period window in the series and predict future n values. Is it possible to implement this approach with your package?

**Comment by franzbischoff** [comment]
Hello. Currently, there is no prediction model using matrix profile. The nearest approach is for state changes, using the [SDTS algorithm](https://matrix-profile-foundation.github.io/tsmp/reference/sdts_predict.html)
