### ISSUE TITLE
tsmp package removed from CRAN?

### ISSUE THREAD

**Issue by csianglim** [matrix-profile-foundation/tsmp#78]
https://cran.rstudio.com/web/packages/tsmp/

Getting this message:

```
Package ‘tsmp’ was removed from the CRAN repository.

Formerly available versions can be obtained from the archive.

Archived on 2020-03-30 as check problems were not corrected in time.

Please use the canonical form https://CRAN.R-project.org/package=tsmp to link to this page.
```

**Comment by franzbischoff** [comment]
Temporarily, due to a RcppParallel dependency bug (not even mine or RcppParallel's fault), I didn't manage to fix in time due to COVID rush... You can use the GitHub version meanwhile.
