### ISSUE TITLE
Area @51

### ISSUE THREAD

**Issue by chris-english** [matrix-profile-foundation/tsmp#82]
Has anyone taken a run at translating Matrix IX to R? I note Franz in @51 that it is not intended, but this creates a strange 'exists in Matlab' (or Octave), but not in R. I've been working on a facsimile that appears to work on the MatrixProfile part, but the index is currently hopeless, so no value, as the two, Profile and index make the whole project work. Is there a translation that has been worked in R, or would someone be willing to eyeball my efforts so far? Thanks.

**Comment by franzbischoff** [comment]
I tried once to use GPU in R without luck...
We can try again.

**Comment by chris-english** [comment]
OK, great. I don't have the advantage of GPU as I develop on a very old box. Just how things are. But GPU should just be a switch rather than threshold to entry. The underlying logic of admissible is agnostic about presence/absence of such acceleration.

I've stitched together a panoply of code that borrows from the spectrum available (in time) from tsmp and my imaginings of what is being done in Octave and how I think that would be done in R, assuming I understood the Octave/Matlab code, which is a rather large assumption. 

 I will attach my wretched code in next comment.

**Comment by chris-english** [comment]
[Stomp_missing_values.tar.gz](https://github.com/matrix-profile-foundation/tsmp/files/5177302/Stomp_missing_values.tar.gz)
Enclosed are:
StompSelfJoinNA.R
CalcLB_dist.R
mass_pre_NA.R
old_fast_avg_sd.R
and data:
Seis_1K_40NA
Seis_1K_noNA
Seis_data - the original paper Seismology data set

Basically trying to use working code already written, to extent possible, so StompSelfJoinNA also employs tsmp::dist_profile.
mass_pre_NA is just a change of tsmp::mass_pre to use old_fast_avg_sd to derive variable 'max_sigma2' (variance) which is calculated once in a non-streaming environment, and seems the basis of Lemire's insight that lower bound is a gamma distribution. I haven't been able to replicate his approach yet as he's seemingly OSX and I'm gcc, and things happen depending on your compiler, but... 

Seis_1K_40NA and Seis_1K_noNA (.rds) are toy sets constructed after running Seis_data$Seis.no.missing through tsmp::stomp, then thru tsmp::find_motifs to locate 2 motifs and surround with other values. NA values in Seis_1K_40NA are [600:639]. window_size(s) are 160 for Seis_1K_40NA and 2000 for Seis_data$(all cases), exclusion_zone is 0.25 for both (though not set by default).

My least comforts:
QZ[1] = firstQZ[i] and friends      - StompSelfJoinNA lines 157:162
MPindex[which(updatePos)] <- i  - StompSelfJoinNA line 183
MatrixProfile[which(updatePos)] = min(distanceProfile[which(updatePos)]) - StompSelfJoinNA line 181
also, probably anything related to exclusion

Thank you for suggesting you'd take a look at this. I imagine if you sent the GPU stuff I'd have many forehead slaps. None of the above is GPU, of course, but I'm trying for working prior to optimization or hardware. 

Thanks,
Chris
